### ISSUE TITLE
Homepage Picture

### ISSUE THREAD

**Issue by hornbergerc** [gkapfham/www#10]
One improvement that I could suggest would be to add a visual or image to the home page to add a better visual for the audience. A visual is appealing to the human eye and looks better then words and links. It also adds character to the website. I have no experience with computer science or programing or coding, so visuals help me and make surfing a website easier. Some examples of visuals could be a picture of students working in a class room or on a project. A picture like that would be fitting for the home page because it's a general picture about computers and students working. To acquire an image like that, you can have a student that have a semi professional or professional camera to take the image. Another way to acquire the image is to ask an art student who is in a photography class and see if they would be willing to take pictures to help them improve their photography skills.

**Comment by Murph45** [comment]
I agree that some sort of image would really help bring the homepage to life. Some thing that give future students a insight into what they will be doing, instead of them just having words immediate thrown at them.

**Comment by zbzoll** [comment]
I also believe that when your are adding the images make sure they fit the specific topic, not just adding it for benefit adding images. Like you shouldn't add a picture of a basketball picture to a computer science instructors website.

**Comment by gkapfham** [comment]
Hello @hornbergerc! Could I trouble you to give this issue a new title? Right now, it does not describe the changes that you are requesting.

**Comment by gkapfham** [comment]
Hello @zbzoll, @hornbergerc, and @Murph45! I agree that it would be a good idea to have an image on the first page of my site. However, I regret that I have not yet found a suitable image for this page! Since it is the main page, it would have to summarize the theme of multiple pages and still be aesthetically pleasing. Can you suggest a specific image that would be suitable? Since I am unable to easily resolve this issue, I will close it now. However, I would welcome any additional feedback that you can share.
