### ISSUE TITLE
Organizational Improvement

### ISSUE THREAD

**Issue by myersj451** [gkapfham/www#12]
Concerning the "Papers" tab, it might help to organize papers into yearly folders or collapsible headers rather than the extensive single page. Users will find themselves continuously scrolling while looking for an article from an earlier year. By condensing the content, the page can become more visually appealing, strongly organized, and easier for the user to find a specific article. The headers should remain organized by year to present a chronological progression of work and focus on the relativity of the paper to the year it was written. 

The "Talks" and "Service" pages could also improve in appearance and accessibility with this format. Both pages, especially the "Service" tab, appear overwhelming with information and links.

**Comment by burrowss** [comment]
I agree with this since it seems that the page is a bit cluttered. By making them collapsible it would definitely help clean up the site and make it more accessible.

**Comment by gkapfham** [comment]
Hello @myersj451 and @burrowss! Thanks for pointing out the fact that it is difficult for people to navigate this page of my web site. As a first step towards solving this problem, I introduced a navigational button that will appear after a person scrolls down far enough in the page. The button will allow someone to return to the top of the page, which is a first step towards improving the navigation. Otherwise, for now, I am going to have to leave these pages as lists until I can write new programs that can analyze them more fully and then generate more sophisticated output.
