### ISSUE TITLE
Redundant sentence structure 

### ISSUE THREAD

**Issue by nadeld** [gkapfham/www#15]
I believe that the sentence: "Finally, he frequently serves the research community as a reviewer for conferences and journals, technical program committee member, conference program co-chair, workshop co-chair, workshop program co-chair, and review panelist at the U.S. National Science Foundation" has unnecessary details on the jobs Professor Kapfhammer has participated in. For example, it is redundant to list "workshop co-chair" and "workshop program co-chair". Instead of stating each job, we can say In addition, he  participated as a reviewer for conferences and journals, most notably he was a review panelist at the U.S. National Science Foundation.

**Comment by cerdamejiaj** [comment]
I agree with you, this is a redundant sentence structure because he uses  "workshop co-chair" and "workshop program co-chair" many times.

**Comment by gkapfham** [comment]
Hello @nadeld and @cerdamejiaj! Thanks for raising this issue. For now, I think that I have to keep the content as it was written since those were the official titles that were given to be by the organizers of the various events. As such, I am going to close this issue since I cannot take steps to resolve it further.
