### ISSUE TITLE
Images Extended

### ISSUE THREAD

**Issue by ZachAndrews98** [gkapfham/www#17]
The image used on this page is 640 x 398 pixels, however the area dedicated to this image is 945 x 430 pixels. This makes it so that if a person clicks on the right side of the image, but not on the image itself, it links to the source. While not critical, this bug could be quite annoying if a person accidentally clicks on that area and then has to return back to your website. So you just have to go back into the source code and change the dimensions of that area to the size of the image. 
Source Link: http://www.cs.allegheny.edu/sites/gkapfham/schedule/
File to Fix (CSS file): https://github.com/gkapfham/www/blob/master/gkapfham/css/bootstrap-slatemod.css
UPDATE: This issue is on each image of your page.

**Comment by Nikki-Luoma** [comment]
This also appears on the "Talks" page as well.

**Comment by gkapfham** [comment]
Hello @ZachAndrews98 and @Nikki-Luoma! Thanks for pointing out this issue. I invested some time trying to discover why this issue is evident in the site, only to learn that it may currently be a fundamental limitation of using Bootstrap to layout the web site. As such, I am not sure that there is an easy way to fix the issue and I am going to close it for now. If you can think of a way to overcome this limitation, let me know!
