### ISSUE TITLE
Research Info Reorganization

### ISSUE THREAD

**Issue by taylor-redman** [gkapfham/www#19]
I would recommended renaming the titles of certain sections within the Software tab. There are three sections, Research Resources, Research Papers, and Research Presentations, that are misleading because at first glance it seems that they are links to the original pieces of work and not the links to the source code. Simply renaming these sub-sections as " Source Code for..." would make it easier for viewers of the page to find information. 
   Another suggestion would be to organize research components into specific projects. A link to a project could contain the source code, software links, papers and presentations relating to that specific project.

**Comment by gkapfham** [comment]
Hi @taylor-redman! Thanks for pointing out that the menu system was not well organized. I have now completely reorganized the menu system and added a drop-down menu that provides quick links to the main pages that visitors will commonly want to view. As I think that this issue is now resolved, I am closing it. You may add extra comments here if you have further insights on how to handle this matter.
