### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by spitalnyd** [gkapfham/www#20]
A problem that I have seen in your website was finding your contact information. The contact information was found in the service tab but took me a little while to find it because the contact information is hidden. So my suggestion is that you make your own tab that is called contact at the top of your website. Another problem I found within the contact site is with in the email address their is a random "click here" link in the middle. That should be removed.
![screenshot from 2017-01-23 15-46-30](https://cloud.githubusercontent.com/assets/25254679/22221981/26837188-e183-11e6-813e-b0b6134879cb.png)
![screenshot from 2017-01-23 15-39-44](https://cloud.githubusercontent.com/assets/25254679/22221988/2c2cd656-e183-11e6-841c-7d51e5b47ce7.png)

**Comment by Nikki-Luoma** [comment]
There is a reason that the e-mail is set up this way. Because of spam bots scanning web pages he needs to keep it the way that it is. Although, I think the contact me page should be a tab on the main page.

**Comment by gkapfham** [comment]
Hello @spitalnyd and @Nikki-Luoma! Thanks for raising and discussing this issue. I agree that the "Contact" page should be more visible and I have fixed that problem in 502ee99. I will close this issue now since I judge that it has been resolved. Please let me know if you think that it is not correctly fixed.
