### ISSUE TITLE
Category titles being centered

### ISSUE THREAD

**Issue by cookc3174** [gkapfham/www#21]
What stands out the most to me while looking at this website is the category titles. To me they look out of place. If you go through the entire website you can see that everything is centered. All the photos, classes, and other resources the website has to offer are all lined up and the category titles just throw it off. You had method you used throughout the website but did not implement it into the titles.

**Comment by gkapfham** [comment]
Hello again @cookc3174! Thanks for pointing out this issue. I have completely rewritten the code that generates the menu at the top of the web site. Also, I liked your idea of a "category page" and went ahead and implemented one for all of the categories assigned to my blog posts. You can find it at:

http://www.cs.allegheny.edu/sites/gkapfham/categories/

Since I think that this issue is now appropriately resolved, I am going to close it. Let me know if I did not resolve the issue in an appropriate fashion.
