### ISSUE TITLE
Error in Dilla article.

### ISSUE THREAD

**Issue by ZachAndrews98** [gkapfham/www#25]
"The downside it that they are harder to find "- "it" needs to be changed to "is".

**Comment by gkapfham** [comment]
Hello @ZachAndrews98! Thanks for pointing out this writing mistake in my web site. I have fixed it in the current version which you can find online now. Since I think that this issue is resolved, I am going to close it. However, if you think that further modifications to the site are needed for this issue, please comment further. Of course, I hope that you will also raise new issues if you find further mistakes.
