### ISSUE TITLE
Topic suggestion

### ISSUE THREAD

**Issue by cerdamejiaj** [gkapfham/www#4]
In the talks sections of your website, there is a lack of content. You have not posted anything since 2015 and this is a concern because the talks section is part of the user experience. You want users to come back to your website and to keep learning from it. A really hot topic to talk about is AI. Many big tech companies like Google, Apple, and IBM are investing a lot of their resources in improving and advancing AIs. Recently Google AI learned how to write more AI software and beaten a human in writing AI software. So far AI has surpassed humans in many ways and this brings many concerns about how AI can impact our society.  How are they going to be beneficial or harmful to our society and how they are going to change us as humans.

**Comment by burrowss** [comment]
I definitely think updating the talks would be helpful in making the site even better. Most of the site seems to be updated this year or late last year so I think this section also needs to be updated.

**Comment by gkapfham** [comment]
Hello @cerdamejiaj and @burrowss! Thanks for raising this issue. I agree with the point that you have made. Due to time constraints since becoming Department Chair, I was not able to travel to conferences or other colleges and universities so that I could give presentations. I am hoping to schedule some presentations for the Fall 2017 and Spring 2018 semesters, which would then lead to new slides being posted here. Also, it is worth noting that many of my papers have presentations associated with them. But, I do not post them on this page because they are already linked on the page for the specific paper. You can find more details about my research papers by visiting:

http://www.cs.allegheny.edu/sites/gkapfham/research/papers/
