### ISSUE TITLE
Improvement for 102, Spring 2017 Page

### ISSUE THREAD

**Issue by Nikki-Luoma** [gkapfham/www#6]
In the course schedule, it would be nice to have a weekly break down of what we are going to do. This page currently breaks the course down into two parts, but I think it would be most helpful if this page had a weekly schedule. Taking the time to add this feature would allow the students to be more prepared when coming to class. For example, certain readings can be listed on this web-page. Also, a weekly break down of the class that includes assignments will allow students to look ahead and be better prepared.

The web page can keep the current layout with the modules with the addition of a weekly breakdown below. I would suggest that each week would be a link and have the link lead to a new page. This new page should include, any readings that will be required for that week, and any assignments we will be assigned that week. There should not be much more details than this on the webpage. Any more information could be considered an overload,but the way the page currently stands there is not enough information.

**Comment by mendezjw** [comment]
I agree with this. The course schedule page lists the content that we will be covering in the class, however it is very unclear when and what material we need to have prepared for the class.

**Comment by ZachAndrews98** [comment]
Having a link on this page to the practicals and any resources that we may or may not have for class that day would also be helpful. It will allow for people to quickly get access to whatever they need without having to go back through the website to find it.

**Comment by liux2** [comment]
Talking about schedules, my suggestion was, put it directly in this page rather than put a link there. It would be easier for students to access.

**Comment by gkapfham** [comment]
Hello everyone! Thanks for suggesting that I create a weekly schedule for my courses. I like this idea and note that it is one that other students have suggested over the years. If possible, I will investigate a way to include this in future courses. I will leave this issue open as a reminder to consider it for the Fall 2017 semester.

With that said, I need to balance out the time that would be required to have pages on my web site that are very frequently updated. Right now, I am already investing a lot of time in developing the web sites and assignments for courses; my preference is to do a very good job at writing and revising the existing content instead of creating too much material that is not as good because I have spread myself too thin!

**Comment by gkapfham** [comment]
Hello @Nikki-Luoma and @mendezjw and @ZachAndrews98 and @liux2, I have taken some of your suggestions for the most recent courses that I taught. Thanks for your ideas, I appreciate them!
